### ISSUE TITLE
הצעת עבודה :-)

### ISSUE THREAD

**Issue by IgalNeeman** [PavelRavvich/vpn-router#1]
היי פבל! יש לך הזדמנות :)
היי, מה שלומך?
התרשמתי מהקוד שלך:-) ונתתי לך כוכב, ויש לי כמה משרות שאולי יעניינו אותך :)
אני עובד עם חברות סטארט-אפ וחברות הייטק יציבות ומבוססות מתחת לרדאר, בתחום הרכבים האוטונומיים, מדיקל, סייבר, פרסום, תרומה לאנושות ועוד.
**חברות מוכנות לשלם הרבה עבור טאלנטים עם ניסיון, תנאים מעולים, ובאופן כללי- קיימים חוזי העסקה שלא ראינו מזה שנים....
אשמח לשוחח ולהתאים עבורך את המשרות הרלוונטיות, בדיסקרטיות מלאה כמובן!
האם יכול להיות רלוונטי?
במידה ואתה רוצה לשמוע פרטים אשמח לקבל ממך הודעה לתיבת המייל שלי igal.neeman@gmail.com
 ומצטער מראש על ה- אישו שפתחתי לך זה הדרך היחידה שהייתה לי ליצור איתך קשר.... 
יגאל 
שלחתי לך את פרטי המשרה למייל.. 
תודה רבה וסליחה על התקלה  שפתחתי לך

**Comment by PavelRavvich** [comment]
> היי פבל! יש לך הזדמנות :) היי, מה שלומך? התרשמתי מהקוד שלך:-) ונתתי לך כוכב, ויש לי כמה משרות שאולי יעניינו אותך :) אני עובד עם חברות סטארט-אפ וחברות הייטק יציבות ומבוססות מתחת לרדאר, בתחום הרכבים האוטונומיים, מדיקל, סייבר, פרסום, תרומה לאנושות ועוד. **חברות מוכנות לשלם הרבה עבור טאלנטים עם ניסיון, תנאים מעולים, ובאופן כללי- קיימים חוזי העסקה שלא ראינו מזה שנים.... אשמח לשוחח ולהתאים עבורך את המשרות הרלוונטיות, בדיסקרטיות מלאה כמובן! האם יכול להיות רלוונטי? במידה ואתה רוצה לשמוע פרטים אשמח לקבל ממך הודעה לתיבת המייל שלי [igal.neeman@gmail.com](mailto:igal.neeman@gmail.com) ומצטער מראש על ה- אישו שפתחתי לך זה הדרך היחידה שהייתה לי ליצור איתך קשר.... יגאל שלחתי לך את פרטי המשרה למייל.. תודה רבה וסליחה על התקלה שפתחתי לך

Ok))))
